credentials:
  usernames:
    michèle:
      email: bischmi4@students.zhaw.ch
      name: Michèle Bischof
      password: $2b$12$.olN/HwQ3VNR21zoD2ksBefpXtXkicRWkerIQtA/FqcTe8lJf0rPC
    guest:
      name: Gast
      password: $2b$12$E95..eFQBJwcKhGe7zynUugVZm5GdTEMcJEyIsTfgshKYVpD2OuAK # To be replaced with hashed password
cookie:
  expiry_days: 30 # number of days until password is asked again
  key: "32ojYU4OormZhyBL4aevv3zEGt62dQHv"
  name: streamlitcookie
