credentials:
  usernames:
    michèle:
      email: bischmi4@students.zhaw.ch
      name: Michèle Bischof
      password: 
    guest:
      name: Gast
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30 # number of days until password is asked again
  key: "32ojYU4OormZhyBL4aevv3zEGt62dQHv"
  name: streamlitcookie
